.PHONY: build test vet fmt lint man man-check

VERSION := $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
COMMIT  := $(shell git rev-parse --short HEAD 2>/dev/null || echo unknown)
DATE    := $(shell date -u +%Y-%m-%dT%H:%M:%SZ)
LDFLAGS := -X github.com/AlbertoBarrago/serval/cmd.version=$(VERSION) \
           -X github.com/AlbertoBarrago/serval/cmd.commit=$(COMMIT) \
           -X github.com/AlbertoBarrago/serval/cmd.date=$(DATE)

build:
	go build -ldflags "$(LDFLAGS)" -o serval .

test:
	go test ./...

vet:
	go vet ./...

fmt:
	@files="$$($$(go env GOROOT)/bin/gofmt -l .)"; if [ -n "$$files" ]; then echo "unformatted files:"; echo "$$files"; exit 1; fi

lint: fmt vet test

man:
	go run ./tools/gendocs docs

man-check: man
	git diff --exit-code --ignore-matching-lines='^[0-9]+-[A-Za-z]+-[0-9]+ Auto generated by spf13/cobra$$' -- docs/*.1 || (echo "docs/*.1 is out of date — run 'make man' and commit the result" && exit 1)
